package ws.mahesh.travelmumbai.utils;

/**
 * Created by Mahesh on 7/19/2014.
 */
public interface TravelInfo {
    public final String AUTO_INFO="TARRIF CARD FOR AUTORICKSHAW FOR MUMBAI METROPOLITAN REGION WITH EFFECT FROM DATE 11.10.2012 \n(a)  Minimum Fare Rs. 15.00           \n(b)  Fare per Kilometer Rs. 9.87  (For Fare Calculation method, pl. see the note below)           \n(c)  25% Additional Fare for journey from 12.00 midnight to 5.00 am.           \n(d)  Luggage charges Rs.3.00 for every package of size greater than 60 X 40 cm other than a briefcase, handbag, attche case.\n\nNote- Fare is payable for a stages of 200 mtrs. till the meters are calibrated as per revised fare \nComplaints : For any complaint about refusal, excess fare, rude behavior etc. against the driver Contact- Toll Free No. 1800 220 110 or write to RTO , Wadala (MH03) or RTO Andheri (MH02) in writing giving date, time and place of offence, nature of the complaint and correct vehicle number.\n\nFor complaints of Thane Region, RTO Thane (MH04),Toll Free No.-1800 225 335\n \nFare Calculation Method- Fare = Distance X Fare Per KM & rounding off to nearest rupee i.e. up to 49 paise to be neglected & 50 paise & above to be rounded to next rupee. eg. For 3.80 KM the fare will be 9.87 X 3.8 = 37.50 i.e. Rs.38, For 5.00 KM the fare will be 9.87 X 5.00 = 49.35 i.e. Rs.49";
    public final String TAXI_INFO="Tariff Card for Black and Yellow Meter Taxi For Mumbai Metropolitan Region with effect from 11/10/2012. \nValid Upto 24/11/2012 or upto the caliberation of meter whichever is earlier. \n(a)  Minimum fare Rs. 19.00 \n(b)  Fare per km.Rs. 12.35 (Rounded off to nearest rupee) \n(c)  25% additional fare for journey from 12.00 midnight to 05.00 a.m. \n(d)  Luggage charges Rs. 6.00 for every package of size greater than 60x 40 cm other than a briefcase, handbag,attach case.\n\nCompalaints :  For any complaint about refusal, excess fare, rude behavior  of driver,  etc,  contact  Toll Free No.1800220110  or write to Regional Transport Office, Mumbai (Central)  (MH-01), Regional Transport Office, Mumbai (West)  (MH-02) or Regional Transport Office, Mumbai (East)  (MH-03), giving date, time and place of offence, nature of the complaints and correct vehicle number. ";

}
